"use client";
import Link from "next/link";
import { MessageSquare, ShieldCheck, Sparkles, UserRound } from "lucide-react";
import { AppShell } from "@/components/layout/AppShell";
import { EmptyState } from "@/components/community/empty-state";
import { communityApi } from "@/lib/community-api";
import { useAsyncData } from "@/lib/use-async-data";
import { formatDateTime } from "@/lib/format";

const icons:Record<string,typeof MessageSquare>={ARTICLE:MessageSquare,COMMENT:MessageSquare,MOMENT:MessageSquare,USER:UserRound};
const labels:Record<string,string>={PENDING:"处理中",UNDER_REVIEW:"审核中",RESOLVED:"已处理",CLOSED:"已关闭"};
export default function ReportsPage(){
 const {data:reports,loading,error}=useAsyncData(()=>communityApi.getMyReports(),[]);
 return <AppShell><main className="mx-auto max-w-[1325px] px-5 pb-16 pt-10 lg:px-8"><div className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_365px]">
 <section className="rounded-[30px] border border-white/80 bg-white/75 p-7 shadow-[0_16px_44px_rgba(85,64,35,.09)] backdrop-blur-md"><header className="text-center"><h1 className="font-serif text-[38px] font-bold tracking-[.08em] text-[#18305c]">举报与申诉</h1><p className="mt-3 text-[15px] text-slate-500">共同维护友善、真诚、温暖的星语社区</p><div className="mx-auto mt-7 flex max-w-[490px] rounded-full border border-[#eadfce] bg-white/70 p-1"><span className="flex h-11 flex-1 items-center justify-center rounded-full bg-[#e89425] text-[16px] font-semibold text-white">我的举报</span><Link href="/appeals" className="flex h-11 flex-1 items-center justify-center rounded-full text-[16px] font-semibold text-[#263961]">我的申诉</Link></div></header><div className="mt-7 overflow-hidden rounded-[23px] border border-[#eee2d6] bg-white/70"><div className="grid grid-cols-[1.1fr_1fr_.72fr_1fr_auto] gap-3 border-b border-[#eee5dc] px-6 py-4 text-sm font-semibold text-[#50607d]"><span>对象类型</span><span>举报内容</span><span>状态</span><span>提交时间</span><span>操作</span></div>{loading?<p className="py-16 text-center text-sm text-slate-400">正在加载举报记录…</p>:error?<p className="py-16 text-center text-sm text-[#b75e42]">{error}</p>:!reports?.length?<EmptyState title="暂无举报记录" description="发现不当内容时，可以通过举报帮助维护社区" actionLabel="新建举报" actionHref="/reports/new"/>:<div>{reports.map(r=>{const I=icons[r.targetType]||MessageSquare;return <div key={r.id} className="grid grid-cols-[1.1fr_1fr_.72fr_1fr_auto] items-center gap-3 border-b border-[#f0e8df] px-6 py-4 last:border-0"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-full bg-[#eef2f8] text-[#304a7c]"><I className="h-5 w-5"/></span><div><b className="text-[#1d315d]">{r.targetType}</b><p className="mt-1 text-xs text-slate-400">对象 ID：{r.targetId}</p></div></div><p className="truncate font-medium text-[#344565]">{r.reason}</p><span className="w-fit rounded-full bg-[#fff0dc] px-3 py-1.5 text-xs font-semibold text-[#d77c29]">{labels[r.status]||r.status}</span><time className="text-sm text-slate-500">{formatDateTime(r.updatedAt)}</time><Link href={`/reports/${r.id}`} className="rounded-full border border-[#eccdab] px-4 py-2 text-sm text-[#486080]">查看详情</Link></div>})}</div>}</div><p className="mt-5 text-center text-sm text-slate-400">若对处理结果有异议，可在结果页面发起申诉，我们会再次认真审核。</p></section>
 <aside className="rounded-[30px] border border-white/80 bg-white/75 p-7 shadow-[0_16px_44px_rgba(85,64,35,.09)]"><div className="text-center"><Sparkles className="mx-auto h-11 w-11 text-[#e59a35]"/><h2 className="mt-3 font-serif text-2xl font-bold text-[#1b315d]">一起守护星语</h2><p className="mt-3 text-sm leading-7 text-slate-500">每一次负责任的举报，都是在为社区点亮一颗星。</p></div><div className="mt-8 space-y-4 text-sm leading-6 text-slate-500"><p><b className="text-[#263961]">友善尊重</b><br/>尊重他人，真诚交流，不攻击、不歧视</p><p><b className="text-[#263961]">真诚分享</b><br/>鼓励真实表达，拒绝谣言与恶意引导</p><p><b className="text-[#263961]">遵守法律</b><br/>不发布违法违规内容，不侵犯他人权益</p></div><div className="mt-7 border-t border-dashed border-[#eadaca] pt-5"><h3 className="font-semibold text-[#263961]">如何正确举报</h3><p className="mt-3 text-sm leading-7 text-slate-500">基于事实，提供准确内容与描述；请耐心等待处理结果。</p></div><Link href="/reports/new" className="mt-7 flex h-12 items-center justify-center rounded-xl bg-[#e88b25] font-semibold text-white">提交新的举报</Link><p className="mt-5 rounded-2xl bg-[#fff5e8] p-4 text-center text-sm text-[#8c6638]">感谢你的信任与参与，让星语社区因你而更美好。</p></aside>
 </div></main></AppShell>;
}
