"use client";

import Link from "next/link";
import { BookOpen, ChevronRight, ShieldCheck, Sparkles } from "lucide-react";
import { AppShell } from "@/components/layout/AppShell";
import { Alert } from "@/components/ui/alert";
import { communityApi } from "@/lib/community-api";
import { useAsyncData } from "@/lib/use-async-data";

const ruleSections = ["总则", "账号与行为规范", "内容规范", "互动规范", "违规处理", "附则"];

export default function RulesPage() {
  const { data: page, loading, error } = useAsyncData(() => communityApi.getGuidePage("community-rules"), []);
  if (loading) return <AppShell><main className="py-28 text-center text-[#768198]">正在加载社区规则…</main></AppShell>;
  if (error || !page) return <AppShell><main className="mx-auto max-w-xl px-5 py-28"><Alert variant="destructive">{error || "社区规则暂不可用"}</Alert><Link href="/guide" className="mt-4 inline-block text-sm text-[#d97925]">查看使用指南</Link></main></AppShell>;
  const paragraphs = (page.body || "").split(/\n+/).filter(Boolean);
  return <AppShell><main className="min-h-screen bg-[radial-gradient(circle_at_16%_3%,rgba(250,217,181,.32),transparent_26%),linear-gradient(135deg,#fffdf9,#fcf4e8)] px-4 pb-12 pt-8 sm:px-6"><div className="mx-auto max-w-[1230px]"><header className="flex flex-col justify-between gap-4 border-b border-[#efe6dc] pb-6 sm:flex-row sm:items-end"><div><p className="flex items-center gap-2 text-[14px] font-medium text-[#dc832d]"><Sparkles className="h-4 w-4"/>社区治理</p><h1 className="mt-3 text-[38px] font-bold tracking-[.08em] text-[#1a315d]">{page.title}</h1><p className="mt-2 text-[16px] text-[#68748a]">共同维护友善、可信赖的星语社区</p></div><Link href="/guide" className="inline-flex items-center gap-2 rounded-xl border border-[#e8ddcf] bg-white/70 px-4 py-2.5 text-[14px] text-[#51627e]"><BookOpen className="h-4 w-4"/>更多指南</Link></header><div className="mt-6 grid gap-6 lg:grid-cols-[250px_minmax(0,1fr)_270px]"><aside className="h-fit rounded-[20px] border border-white/90 bg-white/75 p-5 shadow-[0_12px_30px_rgba(74,53,31,.07)]"><h2 className="text-[17px] font-semibold text-[#263c63]">规则目录</h2><nav className="mt-4 space-y-1">{ruleSections.map((section,index)=><a className={`flex items-center justify-between rounded-lg px-3 py-3 text-[14px] ${index===0?"bg-[#fff1e3] font-semibold text-[#da812c]":"text-[#56647c] hover:bg-[#fbf7f1]"}`} href={`#rule-${index+1}`} key={section}><span><b className="mr-2 font-medium">{index+1}.</b>{section}</span><ChevronRight className="h-4 w-4"/></a>)}</nav></aside><article className="rounded-[22px] border border-white/90 bg-white/75 p-7 shadow-[0_12px_30px_rgba(74,53,31,.07)] sm:p-9"><div className="flex items-center gap-3 rounded-[14px] bg-[#172d59] px-5 py-4 text-white"><ShieldCheck className="h-7 w-7 text-[#f3ba6b]"/><div><b className="text-[18px]">星语社区规则</b><p className="mt-1 text-[13px] text-[#dce6fc]">一起营造友善、真实、有价值的交流环境</p></div></div><div className="xy-reading-copy mt-7 text-[15px] leading-8 text-[#4f5d76]">{ruleSections.map((section,index)=><section className="mb-8" id={`rule-${index+1}`} key={section}><h2 className="text-[23px] font-semibold text-[#203761]">{index+1}. {section}</h2><p className="mt-3 whitespace-pre-wrap">{paragraphs[index] || "请遵循社区基本原则，尊重他人、真诚交流，并共同维护良好的内容与互动秩序。"}</p></section>)}</div></article><aside className="h-fit rounded-[20px] border border-white/90 bg-white/75 p-6 shadow-[0_12px_30px_rgba(74,53,31,.07)]"><h2 className="text-[19px] font-semibold text-[#283e65]">需要帮助？</h2><p className="mt-3 text-[14px] leading-6 text-[#707c91]">如遇到违规内容或需要申诉，可使用治理通道提交说明。</p><Link href="/reports/new" className="mt-5 flex items-center justify-between rounded-xl border border-[#f0cfad] bg-[#fff8ef] px-4 py-3 text-[14px] text-[#db802c]">提交举报 <ChevronRight className="h-4 w-4"/></Link><Link href="/appeals/new" className="mt-3 flex items-center justify-between rounded-xl border border-[#e6e2dc] px-4 py-3 text-[14px] text-[#57657d]">提交申诉 <ChevronRight className="h-4 w-4"/></Link></aside></div></div></main></AppShell>;
}
