import Link from "next/link";
import { useState } from "react";
import { ArrowRight, BookOpen, Clock3, Compass, LoaderCircle, Megaphone, RefreshCw, Sparkles, Star } from "lucide-react";
import { contentHref, type ContentSummary, type TopicSummary } from "@/lib/community-api";
import { formatDateTime } from "@/lib/format";

type Announcement = { id: string; title: string; body?: string | null; publishedAt?: string | null };
type Props = { isGuest: boolean; loading: boolean; greeting: string; greetingMeta?: string | null; continueReading: ContentSummary[]; followUpdates: ContentSummary[]; recommendations: ContentSummary[]; topics: TopicSummary[]; announcements: Announcement[] };

function EmptyState({ title, href, action = "去探索" }: { title: string; href: string; action?: string }) { return <div className="xy-home-v3-empty"><Compass aria-hidden="true" /><p>{title}</p><Link href={href}>{action}<ArrowRight aria-hidden="true" /></Link></div>; }
function SectionTitle({ title, href, action = "查看全部" }: { title: string; href?: string; action?: string }) { return <div className="xy-home-v3-title"><h2><Sparkles aria-hidden="true" />{title}</h2>{href && <Link href={href}>{action}<ArrowRight aria-hidden="true" /></Link>}</div>; }

export function HomePrototypePage({ isGuest, loading, greeting, greetingMeta, continueReading, followUpdates, recommendations, topics, announcements }: Props) {
  const [batch, setBatch] = useState(0);
  const rotate = <T,>(items: T[]) => items.length ? items.slice(batch % items.length).concat(items.slice(0, batch % items.length)) : items;
  const journey = continueReading.slice(0, 4); const visibleRecommendations = rotate(recommendations).slice(0, 4); const visibleTopics = rotate(topics); const featuredTopic = visibleTopics[0];
  return <main className="xy-home-v3" aria-busy={loading}>
    <section className="xy-home-v3-greeting" aria-labelledby="home-greeting-title"><img src="/prototype-assets/home/greeting-avatar.png" alt="" /><div><h1 id="home-greeting-title">{greeting} <span>✦</span></h1><p>{greetingMeta || (isGuest ? "从一篇内容开始，慢慢认识星语社区" : "继续你的阅读与创作旅程")}</p></div><Link href={isGuest ? "/guide" : "/me/history"}><Clock3 aria-hidden="true" />{isGuest ? "初来星语 · 阅读指南" : "查看阅读轨迹"}<ArrowRight aria-hidden="true" /></Link></section>
    <section className="xy-home-v3-first-grid">
      <section className="xy-home-v3-panel xy-home-v3-journey"><SectionTitle title="继续探索" href={isGuest ? "/login" : "/me/history"} action={isGuest ? "登录后继续探索" : "查看全部"} />{loading ? <div className="xy-home-v3-loading"><LoaderCircle className="animate-spin" />正在整理你的阅读轨迹</div> : journey.length ? <div className="xy-home-v3-journey-list">{journey.map((item, i) => <Link href={contentHref(item)} key={item.id} className="xy-home-v3-journey-item"><span className={`xy-home-v3-kind kind-${i % 4}`}><BookOpen aria-hidden="true" /></span><span className="xy-home-v3-item-copy"><b>{item.title}</b><small>{item.summary || "继续上次未完成的内容"}</small></span><span className="xy-home-v3-item-meta">{typeof item.readMinutes === "number" ? `约 ${item.readMinutes} 分钟` : "继续阅读"}<ArrowRight aria-hidden="true" /></span></Link>)}</div> : <EmptyState title={isGuest ? "登录后保存你的阅读、话题与系列进度" : "暂无进行中的内容"} href={isGuest ? "/login" : "/discover"} action={isGuest ? "登录后继续探索" : "探索更多内容"} />}</section>
      <aside className="xy-home-v3-side"><section className="xy-home-v3-panel xy-home-v3-announcements"><SectionTitle title="星语公告" href="/announcements" />{announcements.length ? <ul>{announcements.slice(0, 3).map(a => <li key={a.id}><Link href={`/announcements/${a.id}`}><b>{a.title}</b><small>{a.publishedAt ? formatDateTime(a.publishedAt) : "星语公告"}</small></Link></li>)}</ul> : <EmptyState title="暂无星语公告" href="/announcements" action="查看公告中心" />}</section><section className="xy-home-v3-panel xy-home-v3-follow"><SectionTitle title="关注动态" href={isGuest ? "/moments" : "/me/following"} />{followUpdates.length ? <ul>{followUpdates.slice(0, 3).map(item => <li key={item.id}><span>{item.authorName?.slice(0, 1) || "星"}</span><Link href={contentHref(item)}><b>{item.authorName || "星语创作者"}</b><small>{item.title}<em>{item.updatedAt ? formatDateTime(item.updatedAt) : "最近更新"}</em></small></Link></li>)}</ul> : <EmptyState title="暂无关注动态" href={isGuest ? "/moments" : "/me/following"} action={isGuest ? "看看动态" : "管理关注"} />}</section></aside>
    </section>
    <section className="xy-home-v3-recommend"><header><div><span>EXPLORE NEXT</span><h2>为你推荐</h2><p>从正在发生的内容里，找到下一篇值得读的故事。</p></div><button type="button" aria-label="换一批" onClick={() => setBatch(value => value + 1)}><RefreshCw aria-hidden="true" />换一批</button></header><div className="xy-home-v3-recommend-grid"><section className="xy-home-v3-featured"><SectionTitle title="内容精选" href="/discover" action="更多内容" />{visibleRecommendations.length ? <div className="xy-home-v3-content-list">{visibleRecommendations.map((item, i) => <Link href={contentHref(item)} key={item.id} className="xy-home-v3-content-card"><span className="xy-home-v3-content-type">{item.objectType === "series" ? "系列" : "文章"}</span><h3>{item.title}</h3><p>{item.summary || "来自星语社区的精选内容"}</p><small>{item.authorName || "星语创作者"}{item.readMinutes ? ` · ${item.readMinutes} min` : ""}</small><span className={`xy-home-v3-card-art art-${i % 4}`} aria-hidden="true" /></Link>)}</div> : <EmptyState title="暂时没有推荐内容" href="/discover" />}</section><aside className="xy-home-v3-radar"><SectionTitle title="话题雷达" href="/topics" action="浏览话题" />{featuredTopic ? <><Link href={`/topics/${featuredTopic.slug}`} className="xy-home-v3-feature-topic"><Star aria-hidden="true" /><b>#{featuredTopic.name}</b><p>{featuredTopic.description || "正在升温的讨论方向"}</p><small>{featuredTopic.contentCount ?? 0} 条内容 · {featuredTopic.followerCount ?? 0} 人关注</small></Link><div className="xy-home-v3-topic-grid">{visibleTopics.slice(1, 5).map(topic => <Link href={`/topics/${topic.slug}`} key={topic.id}><b># {topic.name}</b><small>{topic.contentCount ?? 0} 条内容</small></Link>)}</div></> : <EmptyState title="暂无热门话题" href="/topics" action="浏览话题广场" />}</aside></div></section>
  </main>;
}
