<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>top.pxczxn</groupId>
        <artifactId>xingyu-backend</artifactId>
        <version>1.0.0</version>
    </parent>

    <artifactId>xingyu-core</artifactId>
    <packaging>pom</packaging>
    <name>Xingyu Core</name>
    <description>业务核心层 - 业务模块</description>

    <modules>
        <module>xingyu-system</module>
        <module>xingyu-file</module>
        <module>xingyu-gen</module>
        <module>xingyu-auth</module>
        <module>xingyu-community</module>
        <module>xingyu-platform</module>
    </modules>
</project>
